name: se7ety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  
  cloudinary_public: ^0.23.1

  cloudinary_flutter: ^1.0.0
  http: ^1.4.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.2.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
